config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    def hello
            render plain: "hello world!"
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :page_title, except: [ :home ]
  
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
  
  private

  #I think because this is a before_action, it doesnt have to manually be called to each methods
  def page_title
     @title = self.action_name.capitalize 
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
    #When there is no title, the title is "Sample App"

    def default_title(page_title = '' )
        main_title = 'Sample App'

        if page_title.nil? || page_title.empty?
            main_title
            else
                page_title + " | " + main_title
        end
    end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
 <div class="fixed-bottom row" id="footer">
          <footer class= "mx-auto">
              <p class = "small">
                    <%= Time.now.year %> |
                    <a href="https://github.com/lovemercybiz" class="text-dark">Love Mercy</a>
              <p>
          </footer>
    </div>

app/views/layouts/_jumbotron.html.erb
   <main role="main" class="container  pt-3">
      <div class="jumbotron">
            <%= yield %>
                  <button type="button" class="btn btn-primary btn-lg mt-2">Sign up now!</button>
          </div>
    </main>

app/views/layouts/_navbar.html.erb
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <%= link_to "Sample App", root_path, class: "navbar-brand", id: "logo" %>
        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav ml-auto" id="nav-menu">
            <%# <li class="nav-item"> %>
              <%# <li>= link_to "Home", root_path, class: "nav-link"</li> %>
            <%# </li> %>

            <li class="nav-item">
              <li><%= link_to "Help", help_path,  class: "nav-link" %></li>
            </li>

              <li class="nav-item">
                  <li><%= link_to "About", about_path, class: "nav-link" %></li>
            </li>

              <li class="nav-item">
                    <li><%= link_to "Contact", contact_path, class: "nav-link" %></li>
            </li>

             <li class="nav-item">
                    <li><%= link_to "Log in", "#", class: "nav-link" %></li>
            </li>

          </ul>

        </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= default_title(@title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

      <%= render 'layouts/navbar'%>

    <%= render 'layouts/jumbotron'%>

    <%= link_to image_tag("rails.png", alt: "Rails logo",class:"img-fluid"), "https://rubyonrails.org/" %>
    <%#= link_to image_tag("kitten.jpg", alt: "kitten") %>

 <%= render 'layouts/footer'%>

  </body>
</html>

app/views/static_pages/about.html.erb
<h1>About</h1>
    <p>The <a href="http://www.railstutorial.org/"> 
        <em>Ruby on Rails Tutorial</em></a> is a 
            <a href="http://www.railstutorial.org/book">book</a>
                 and <a href="http://screencasts.railstutorial.org/">screencast series</a>
                        to teach web development with 
                                <a href="http://rubyonrails.org/">Ruby on Rails</a>.
    </p>

   <p> This is the sample application for the tutorial. </p>
               

app/views/static_pages/contact.html.erb
<h1>Contact</h1>
    <p> Contact the Ruby on Rails Tutorial about the sample app at the
        <a href="http://www.railstutorial.org/contact">contact page</a>.
    </p>

app/views/static_pages/help.html.erb
<h1>Help</h1>
    <p> Get help on the Ruby on Rails Tutorial at the
            <a href="http://www.railstutorial.org/help">Rails Tutorial help page</a>.
       </p>
       
       <p>
        To get help on this sample app, see the
            <a href="http://www.railstutorial.org/book">
            <em>Ruby on Rails Tutorial</em> 
            book</a>.
</p>

app/views/static_pages/home.html.erb
<h1>Sample App</h1>

<p> This is the home page for the
        <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a> 
        sample application.
</p>